create table public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.menu_apps (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 60),
  url text not null check (url ~ '^https://'),
  emoji text not null check (char_length(btrim(emoji)) between 1 and 12),
  sort_order integer not null default 0 check (sort_order >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.menu_app_settings (
  id smallint primary key default 1 check (id = 1),
  theme text not null default 'claro' check (theme in ('claro', 'escuro')),
  background text not null default 'gta_6.png'
    check (background in ('gta_6.png', 'spider_man.png', 'combat_8.png', 'prime.png')),
  updated_at timestamptz not null default now()
);

alter table public.app_admins enable row level security;
alter table public.menu_apps enable row level security;
alter table public.menu_app_settings enable row level security;

revoke all on public.app_admins from anon, authenticated;
revoke all on public.menu_apps from anon, authenticated;
revoke all on public.menu_app_settings from anon, authenticated;

grant select on public.app_admins to authenticated;
grant select on public.menu_apps to anon, authenticated;
grant insert, update, delete on public.menu_apps to authenticated;
grant usage, select on sequence public.menu_apps_id_seq to authenticated;
grant select on public.menu_app_settings to anon, authenticated;
grant insert, update on public.menu_app_settings to authenticated;

create policy "admins_can_read_own_membership"
on public.app_admins
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "public_can_read_active_apps"
on public.menu_apps
for select
to anon, authenticated
using (
  is_active
  or exists (
    select 1 from public.app_admins
    where app_admins.user_id = (select auth.uid())
  )
);

create policy "admins_can_insert_apps"
on public.menu_apps
for insert
to authenticated
with check (
  exists (
    select 1 from public.app_admins
    where app_admins.user_id = (select auth.uid())
  )
);

create policy "admins_can_update_apps"
on public.menu_apps
for update
to authenticated
using (
  exists (
    select 1 from public.app_admins
    where app_admins.user_id = (select auth.uid())
  )
)
with check (
  exists (
    select 1 from public.app_admins
    where app_admins.user_id = (select auth.uid())
  )
);

create policy "admins_can_delete_apps"
on public.menu_apps
for delete
to authenticated
using (
  exists (
    select 1 from public.app_admins
    where app_admins.user_id = (select auth.uid())
  )
);

create policy "public_can_read_settings"
on public.menu_app_settings
for select
to anon, authenticated
using (true);

create policy "admins_can_insert_settings"
on public.menu_app_settings
for insert
to authenticated
with check (
  id = 1
  and exists (
    select 1 from public.app_admins
    where app_admins.user_id = (select auth.uid())
  )
);

create policy "admins_can_update_settings"
on public.menu_app_settings
for update
to authenticated
using (
  exists (
    select 1 from public.app_admins
    where app_admins.user_id = (select auth.uid())
  )
)
with check (
  id = 1
  and exists (
    select 1 from public.app_admins
    where app_admins.user_id = (select auth.uid())
  )
);

insert into public.menu_apps (name, url, emoji, sort_order) values
('PDV - TAPIMOVEL', 'https://script.google.com/macros/s/AKfycbyOs3tHhYh3zGTOGYNSYgNxTz7Lcu6bb_ic0w3Z2jK2zt46Xp3Ie_XRHZnfIJ5qY9lp/exec', '🚗🌮', 1),
('ALENCAR FINANÇAS', 'https://script.google.com/macros/s/AKfycbyom0t8Hd9BroTzAWcNnkeqhHNvEi6gxaQcaQcExShDQv4vodPwHAQaJ0-vVc4_WIpl/exec', '💰', 2),
('ALENCAR FRETES', 'https://alencar1992.github.io/ALENCAR_FRETES/', '🏍️💨', 3),
('CALCULADORA FRETES', 'https://alencar1992.github.io/ALENCAR_FRETES/calculadora.html', '📝', 4),
('GESTÃO DE ENTREGAS', 'https://script.google.com/macros/s/AKfycbyRQRB6p7ORaWgEro0KhS7rQ784g206cj0HiktkUjcn2TludQ4MHvqbRo163KHPpKYOIA/exec', '🏍️📦', 5),
('PRIPEL GESTÃO', 'https://alencar1992.github.io/pripel-gestao-app/', '📊', 6),
('GESTÃO FINANÇAS CASA', 'https://script.google.com/macros/s/AKfycbyIiVuIrpUdGic39iyVG7wngs8Jtx7CgN0AMGUNODrIHad2a57ND1HFPj37hgt_PTLw/exec', '🏧', 7),
('TAREFAS PRI', 'https://script.google.com/macros/s/AKfycbzpYzG0rHm_Sz2CHAC76ySn2Y7pNPSOJ7Z0ETogoQortLQEiUeloP6inwcqncTgoztf/exec', '🧮', 8),
('MIKAA NAILS', 'https://alencar1992.github.io/naailsby.mikaa/admin.html', '💅', 9),
('CARDÁPIO CLIENTE', 'https://script.google.com/macros/s/AKfycbyOs3tHhYh3zGTOGYNSYgNxTz7Lcu6bb_ic0w3Z2jK2zt46Xp3Ie_XRHZnfIJ5qY9lp/exec?modo=cliente', '🛎️', 10),
('gemini AI', 'https://gemini.google.com/', '🤖', 11),
('HUB FINANCE', 'https://alencar1992.github.io/FINANCE-HUB/', '📊', 12),
('TAPIMOVEL 2.0', 'https://alencar1992.github.io/TAPIMOVEL.20/frontend/index.html', '🌮🚗', 13),
('CARDAPIO TAPIOCA CLIENTE', 'https://alencar1992.github.io/TAPIMOVEL.20/frontend/cliente.html', '🌮', 14);

insert into public.menu_app_settings (id, theme, background)
values (1, 'escuro', 'spider_man.png');
